### ISSUE TITLE
How to set the Accelerometer range and increase the sampling speed? Thx

### ISSUE THREAD

**Issue by AK51** [romybompart/py_imu_mpu6050#2]
Hi, I need to sample the accelerometer at 1000 Hz, may I know how to the I2C speed?
For the accelerometer, I need +/- 4g. How to use the set_acel_range function?

Thanks

**Comment by romybompart** [comment]
Hello AK51, the I2C speed can be configured by using the device tree. 
Any linux device has a i2c clock speed fixed. 

**Raspberry Pi (3.18 kernel or later)**
Fortunetly for the raspberry kernel, it is easy to implement by using the dtparam in the config.txt file. 

`sudo nano /boot/config.txt`
INSERT 
`dtparam=i2c_baudrate=400000`
THEN
`sudo reboot`

**Notes for the Raspberry Pi 3B, 3B+ and Zero W**

The I2C controller on the Raspberry Pi 3B, 3B+ and Zero W has its clock linked to the VPU core so as the VPU frequency changes depending on processor load so does the clock rate of the I2C bus.  This can cause problems with any devices that expect a constant clock rate during communication.

To solve this issue the VPU core frequency must be set to a fixed frequency by editing /boot/config.txt.  Open the file with nano using the command:

sudo nano /boot/config.txt
Add the following text to the bottom of the file.

`core_freq=250`
Save your changes, exit the nano editor and reboot

`sudo reboot`

**For beaglebone in the other hand. You need to create a new overlay for the device tree** 

https://stackoverflow.com/questions/33549211/how-to-add-i2c-devices-on-the-beaglebone-black-using-device-tree-overlays

**Comment by romybompart** [comment]
About the accelerometer range, indeed can be: 
+/- 2 , +/- 4, +/-8 and +/- 16.

To change the scale. after you create the object you can set the accell range. 
       
```
from imu_mpu6050 import MPU6050
i2c = busio.I2C(SCL,SDA)
IMU = MPU6050(i2c)
IMU.set_accel_range(IMU.ACCEL_RANGE_4G)
```

Let me know if you solve it.

**Comment by romybompart** [comment]
> Hi, I need to sample the accelerometer at 1000 Hz, may I know how to the I2C speed?
> For the accelerometer, I need +/- 4g. How to use the set_acel_range function?
> 
> Thanks

Since no feedback was provided I will close this issue .
